version: "3.8"
services:
  node-api:
    build:
      context: .
        dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
  python-service:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "5000:5000"
